version: 2.1

orbs:
  docker: circleci/docker@3.0.1

workflows:
  docker:
    jobs:
      - docker/publish:
          context:
            - chunk-cli-docker-temp
          image: circleci/cli-releaser
          tag: "0.1.0,latest"
          dockerfile: Dockerfile.ci
