version: 2.1

jobs:
  dockerbuild:
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --file Dockerfile.ci .

workflows:
  docker:
    jobs:
      - dockerbuild
