version: 2.1

jobs:
  dockerbuild:
    executor: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - run: docker build --file Dockerfile.ci .

workflows:
  docker:
    jobs:
      - dockerbuild
