version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.4.0

executors:
  releaser:
    docker:
      - image: circleci/cli-releaser:0.1.0
    environment:
      BUN_INSTALL: /home/circleci/.bun
      PATH: /home/circleci/.bun/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

jobs:
  lint:
    executor: releaser
    resource_class: medium
    steps:
      - setup
      - run:
          name: Biome lint & format check
          command: bun run lint
      - run:
          name: TypeScript type check
          command: bun run typecheck

  test:
    executor: releaser
    resource_class: medium
    steps:
      - setup
      - run:
          name: Run unit tests
          command: bun run test:unit
          no_output_timeout: 90s

workflows:
  ci:
    jobs:
      - shellcheck/check
      - lint
      - test:
          context:
            - chunk-cli-test
          requires:
            - shellcheck/check
            - lint
