version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.4.0

executors:
  releaser:
    docker:
      - image: circleci/cli-releaser:0.2.0

jobs:
  lint:
    executor: releaser
    resource_class: medium
    steps:
      - checkout
      - run: bun install
      - run: bun run lint
      - run: bun run typecheck

  test:
    executor: releaser
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: bun run test:unit
          no_output_timeout: 90s

workflows:
  ci:
    jobs:
      - shellcheck/check
      - lint
      - test:
          context:
            - chunk-cli-test
          requires:
            - shellcheck/check
            - lint
